font_family 		    JetBrains Mono
font_size 		        11

background_opacity 	    0.95

window_padding_width 	8

cursor_shape 		    beam

enable_audio_bell 	    no

remember_windows_size 	no
initial_windows_width 	110
initial_windows_height 	35
