# Font
font_family 				Hack Nerd Font
font_size 					11

# Background
background_opacity 			0.85

# Cursor
cursor_shape 				beam
cursor_blink_interval		0.5

# Performance
repaint_delay				10
input_delay					3

# Scroll
scrollback_lines			10000

# Tabs
tab_bar_style				powerline

# Window
window_padding_width 		8
confirm_os_window_close		0

enable_audio_bell 			no

remember_window_size 		no
initial_window_width 		108
initial_window_height 		35
